In [140]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

pd.set_option('max_columns', None)

In [141]:
X = pd.read_csv("Data/train.csv")
del X["Unnamed: 0"] #just order
del X["Time"] #for now

fir_cols = ["Division",
            # "Time",
            "home_team",
            "away_team",
            "Referee", 
            "home_coef", 
            "draw_coef", 
            "away_coef"
            ]
X.head()

,Division,home_team,away_team,full_time_home_goals,full_time_away_goals,half_time_home_goals,half_time_away_goals,Referee,home_shots,away_shots,home_shots_on_target,away_shots_on_target,home_fouls,away_fouls,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,home_coef,draw_coef,away_coef
0,0,152.0,426.0,0.0,0.0,0.0,0.0,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.627690,3.577721,2.198600
1,0,216.0,341.0,2.0,2.0,0.0,1.0,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.608321,4.251999,6.533805
2,0,223.0,119.0,2.0,2.0,2.0,0.0,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.166811,3.486596,3.821467
3,0,68.0,137.0,2.0,1.0,0.0,1.0,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.259244,3.592401,3.460103
4,1,425.0,225.0,2.0,2.0,1.0,0.0,-1,13.0,11.0,5.0,7.0,18.0,15.0,4.0,10.0,3.0,4.0,1.0,0.0,2.424278,3.414191,3.282876

In [142]:
X.columns

Index(['Division', 'home_team', 'away_team', 'full_time_home_goals',
       'full_time_away_goals', 'half_time_home_goals', 'half_time_away_goals',
       'Referee', 'home_shots', 'away_shots', 'home_shots_on_target',
       'away_shots_on_target', 'home_fouls', 'away_fouls', 'home_corners',
       'away_corners', 'home_yellow_cards', 'away_yellow_cards',
       'home_red_cards', 'away_red_cards', 'home_coef', 'draw_coef',
       'away_coef'],
      dtype='object')

In [143]:
for var in X.columns: 
    print(X[var].value_counts())

# Categorical_cols = ["full_time_home_goals", "full_time_away_goals", "half_time_home_goals", "away_corners","home_yellow_cards","away_yellow_cards","home_red_cards"]

7     3281
11    3260
9     3243
6     2630
14    2531
10    2238
12    2223
15    2216
19    1847
18    1836
13    1803
0     1789
2     1774
5     1749
8     1641
17    1411
1     1321
16    1225
4     1000
3      974
Name: Division, dtype: int64
394.0    137
52.0     137
409.0    137
320.0    137
290.0    137
        ...
59.0      14
196.0     14
490.0     12
243.0     10
314.0      5
Name: home_team, Length: 464, dtype: int64
226.0    137
367.0    137
337.0    137
438.0    137
132.0    137
        ...
196.0     14
490.0     14
244.0     12
243.0     10
314.0      7
Name: away_team, Length: 464, dtype: int64
1.0     13362
2.0      9704
0.0      9411
3.0      4881
4.0      1817
5.0       568
6.0       194
7.0        43
8.0         9
9.0         2
10.0        1
Name: full_time_home_goals, dtype: int64
1.0    14195
0.0    13149
2.0     7980
3.0     3200
4.0     1053
5.0      324
6.0       72
7.0       13
8.0        5
9.0        1
Name: full_time_away_goals, dtype: int64
0.0    20881
1.0    13622
2.0     4404
3.0      893
4.0      166
5.0       24
6.0        2
Name: half_time_home_goals, dtype: int64
0.0    24407
1.0    12017
2.0     2925
3.0      553
4.0       75
5.0       14
6.0        1
Name: half_time_away_goals, dtype: int64
-1      28166
 6        186
 15       172
 2        169
 12       169
        ...
 132        1
 131        1
 121        1
 89         1
 118        1
Name: Referee, Length: 160, dtype: int64
11.0    2015
12.0    1977
13.0    1921
10.0    1913
14.0    1816
9.0     1784
15.0    1533
8.0     1472
16.0    1422
7.0     1219
17.0    1144
18.0     934
6.0      925
19.0     756
20.0     614
5.0      572
21.0     429
22.0     367
4.0      298
23.0     298
24.0     191
3.0      173
25.0     164
26.0     103
27.0      86
2.0       52
28.0      49
29.0      42
30.0      30
31.0      27
1.0       18
32.0      15
33.0      10
36.0       7
37.0       5
34.0       5
35.0       4
43.0       2
0.0        2
39.0       2
42.0       1
38.0       1
Name: home_shots, dtype: int64
9.0     2373
10.0    2338
8.0     2164
11.0    2093
7.0     2029
12.0    1873
13.0    1617
6.0     1592
14.0    1302
5.0     1188
15.0    1124
16.0     842
4.0      809
17.0     639
18.0     480
3.0      438
19.0     330
20.0     251
2.0      215
21.0     184
22.0     131
23.0      91
1.0       78
24.0      62
26.0      40
25.0      39
27.0      22
0.0       15
28.0      15
29.0       9
30.0       7
31.0       2
32.0       2
35.0       2
33.0       1
34.0       1
Name: away_shots, dtype: int64
4.0     3934
3.0     3745
5.0     3634
6.0     2990
2.0     2625
7.0     2121
8.0     1486
1.0     1263
9.0      908
10.0     544
11.0     370
0.0      365
12.0     173
13.0     111
14.0      61
15.0      33
16.0      15
18.0       7
17.0       7
19.0       4
20.0       2
Name: home_shots_on_target, dtype: int64
3.0     4535
4.0     4156
2.0     3861
5.0     3206
6.0     2362
1.0     2255
7.0     1431
8.0      853
0.0      715
9.0      474
10.0     259
11.0     150
12.0      69
13.0      33
14.0      18
15.0      11
16.0       5
17.0       2
18.0       1
20.0       1
19.0       1
Name: away_shots_on_target, dtype: int64
11.0    2257
12.0    2242
10.0    2185
13.0    2119
9.0     2066
14.0    1854
8.0     1595
15.0    1529
16.0    1282
7.0     1256
17.0    1016
6.0      829
18.0     718
19.0     571
5.0      468
20.0     372
4.0      282
21.0     273
22.0     209
23.0     135
3.0      111
24.0      81
25.0      53
26.0      47
2.0       43
27.0      15
28.0      13
0.0        8
29.0       8
1.0        6
30.0       3
33.0       1
31.0       1
Name: home_fouls, dtype: int64
12.0    2290
11.0    2241
13.0    2199
10.0    2040
14.0    1916
9.0     1817
15.0    1726
16.0    1467
8.0     1388
17.0    1175
7.0      979
18.0     899
6.0      652
19.0     650
20.0     492
5.0      385
21.0     332
22.0     229
4.0      196
23.0     179
24.0      92
3.0       80
25.0      75
26.0      39
27.0      29
2.0       24
1.0       17
28.0      15
29.0       9
0.0        7
30.0       7
32.0       2
Name: away_fouls, dtype: int64
5.0     3474
4.0     3355
6.0     3119
3.0     2708
7.0     2589
8.0     2048
2.0     1889
9.0     1393
10.0    1042
1.0      878
11.0     670
12.0     410
13.0     246
0.0      246
14.0     149
15.0      88
16.0      44
18.0      18
17.0      17
19.0       5
20.0       4
21.0       3
22.0       2
26.0       1
Name: home_corners, dtype: int64
4.0     3883
3.0     3697
5.0     3497
2.0     2877
6.0     2726
7.0     2042
1.0     1805
8.0     1306
9.0      867
0.0      531
10.0     514
11.0     298
12.0     145
13.0     109
14.0      51
15.0      26
16.0      12
18.0       5
17.0       4
21.0       2
19.0       1
Name: away_corners, dtype: int64
1.0     7550
2.0     6521
0.0     4548
3.0     3662
4.0     1496
5.0      458
6.0      125
7.0       29
8.0        7
11.0       1
Name: home_yellow_cards, dtype: int64
2.0    6805
1.0    6484
3.0    4672
0.0    3241
4.0    2173
5.0     757
6.0     206
7.0      46
8.0      11
9.0       3
Name: away_yellow_cards, dtype: int64
0.0    22418
1.0     1884
2.0       95
9.0        1
Name: home_red_cards, dtype: int64
0.0    21772
1.0     2452
2.0      164
3.0       10
Name: away_red_cards, dtype: int64
2.217507     21
2.495780     17
2.245403     13
2.574257     13
2.731092     12
             ..
1.870866      1
12.864620     1
1.901952      1
1.228525      1
2.162520      1
Name: home_coef, Length: 33498, dtype: int64
3.439153    24
3.422549    20
3.394625    18
3.492849    18
3.520352    17
            ..
3.508682     1
3.567208     1
3.515857     1
5.251835     1
3.500000     1
Name: draw_coef, Length: 32200, dtype: int64
3.094767    13
3.520352    12
2.832244    12
3.120559    12
3.006138    12
            ..
8.540005     1
6.158557     1
5.340548     1
2.906056     1
3.015064     1
Name: away_coef, Length: 34035, dtype: int64

In [144]:
print(X.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39992 entries, 0 to 39991
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Division              39992 non-null  int64
 1   home_team             39992 non-null  float64
 2   away_team             39992 non-null  float64
 3   full_time_home_goals  39992 non-null  float64
 4   full_time_away_goals  39992 non-null  float64
 5   half_time_home_goals  39992 non-null  float64
 6   half_time_away_goals  39992 non-null  float64
 7   Referee               39992 non-null  int64
 8   home_shots            24398 non-null  float64
 9   away_shots            24398 non-null  float64
 10  home_shots_on_target  24398 non-null  float64
 11  away_shots_on_target  24398 non-null  float64
 12  home_fouls            23648 non-null  float64
 13  away_fouls            23648 non-null  float64
 14  home_corners          24398 non-null  float64
 15  away_corners          24398 non-null  float64
 16  home_yellow_cards     24397 non-null  float64
 17  away_yellow_cards     24398 non-null  float64
 18  home_red_cards        24398 non-null  float64
 19  away_red_cards        24398 non-null  float64
 20  home_coef             39992 non-null  float64
 21  draw_coef             39992 non-null  float64
 22  away_coef             39992 non-null  float64
dtypes: float64(21), int64(2)
memory usage: 7.0 MB
None

In [145]:
for var in X.columns:
    print(var, ' : ', len(X[var].unique()), ' labels')

Division  :  20  labels
home_team  :  464  labels
away_team  :  464  labels
full_time_home_goals  :  11  labels
full_time_away_goals  :  10  labels
half_time_home_goals  :  7  labels
half_time_away_goals  :  7  labels
Referee  :  160  labels
home_shots  :  43  labels
away_shots  :  37  labels
home_shots_on_target  :  22  labels
away_shots_on_target  :  22  labels
home_fouls  :  34  labels
away_fouls  :  33  labels
home_corners  :  25  labels
away_corners  :  22  labels
home_yellow_cards  :  11  labels
away_yellow_cards  :  11  labels
home_red_cards  :  5  labels
away_red_cards  :  5  labels
home_coef  :  33498  labels
draw_coef  :  32200  labels
away_coef  :  34035  labels

In [146]:
X.describe()

,Division,home_team,away_team,full_time_home_goals,full_time_away_goals,half_time_home_goals,half_time_away_goals,Referee,home_shots,away_shots,home_shots_on_target,away_shots_on_target,home_fouls,away_fouls,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,home_coef,draw_coef,away_coef
count,39992.000000,39992.000000,39992.000000,39992.000000,39992.000000,39992.000000,39992.000000,39992.000000,24398.000000,24398.000000,24398.000000,24398.000000,23648.000000,23648.000000,24398.000000,24398.000000,24397.000000,24398.000000,24398.000000,24398.000000,39992.000000,39992.000000,39992.000000
mean,9.760827,248.756676,248.720094,1.477445,1.154206,0.647755,0.497650,15.344719,12.887286,10.524018,4.897123,4.000328,12.141027,12.679677,5.749119,4.658497,1.675288,1.978031,0.085376,0.115173,2.685056,3.872743,4.490756
std,5.269941,144.133197,144.101377,1.245247,1.120573,0.803566,0.713799,32.457316,5.042720,4.418543,2.616094,2.320526,4.208618,4.236110,2.956443,2.626982,1.280404,1.352104,0.298042,0.343244,1.718923,1.132322,3.629462
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.047743,2.524868,1.102549
25%,6.000000,120.000000,120.000000,1.000000,0.000000,0.000000,0.000000,-1.000000,9.000000,7.000000,3.000000,2.000000,9.000000,10.000000,4.000000,3.000000,1.000000,1.000000,0.000000,0.000000,1.882522,3.389876,2.759872
50%,10.000000,252.000000,252.000000,1.000000,1.000000,0.000000,0.000000,-1.000000,12.000000,10.000000,5.000000,4.000000,12.000000,12.000000,5.000000,4.000000,2.000000,2.000000,0.000000,0.000000,2.291583,3.562471,3.568531
75%,14.000000,377.000000,377.000000,2.000000,2.000000,1.000000,1.000000,13.000000,16.000000,13.000000,6.000000,5.000000,15.000000,15.000000,8.000000,6.000000,2.000000,3.000000,0.000000,0.000000,2.836276,3.888294,4.839698
max,19.000000,494.000000,494.000000,10.000000,9.000000,6.000000,6.000000,158.000000,43.000000,35.000000,20.000000,20.000000,33.000000,32.000000,26.000000,21.000000,11.000000,9.000000,9.000000,3.000000,36.083420,28.959884,66.225294

In [147]:
X.isna().any()

Division                False
home_team               False
away_team               False
full_time_home_goals    False
full_time_away_goals    False
half_time_home_goals    False
half_time_away_goals    False
Referee                 False
home_shots               True
away_shots               True
home_shots_on_target     True
away_shots_on_target     True
home_fouls               True
away_fouls               True
home_corners             True
away_corners             True
home_yellow_cards        True
away_yellow_cards        True
home_red_cards           True
away_red_cards           True
home_coef               False
draw_coef               False
away_coef               False
dtype: bool

In [148]:
X['home_shots'].fillna(X['home_shots'].median(), inplace=True)
X['away_shots'].fillna(X['away_shots'].median(), inplace=True)
X['home_shots_on_target'].fillna(X['home_shots_on_target'].median(), inplace=True)
X['away_shots_on_target'].fillna(X['away_shots_on_target'].median(), inplace=True)
X['home_fouls'].fillna(X['home_fouls'].median(), inplace=True)
X['away_fouls'].fillna(X['away_fouls'].median(), inplace=True)
X['home_corners'].fillna(X['home_corners'].median(), inplace=True)
X['away_corners'].fillna(X['away_corners'].median(), inplace=True)
X['home_yellow_cards'].fillna(X['home_yellow_cards'].median(), inplace=True)
X['away_yellow_cards'].fillna(X['away_yellow_cards'].median(), inplace=True)
X['home_red_cards'].fillna(X['home_red_cards'].median(), inplace=True)
X['away_red_cards'].fillna(X['away_red_cards'].median(), inplace=True)

In [149]:
X.head()

,Division,home_team,away_team,full_time_home_goals,full_time_away_goals,half_time_home_goals,half_time_away_goals,Referee,home_shots,away_shots,home_shots_on_target,away_shots_on_target,home_fouls,away_fouls,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,home_coef,draw_coef,away_coef
0,0,152.0,426.0,0.0,0.0,0.0,0.0,-1,12.0,10.0,5.0,4.0,12.0,12.0,5.0,4.0,2.0,2.0,0.0,0.0,3.627690,3.577721,2.198600
1,0,216.0,341.0,2.0,2.0,0.0,1.0,-1,12.0,10.0,5.0,4.0,12.0,12.0,5.0,4.0,2.0,2.0,0.0,0.0,1.608321,4.251999,6.533805
2,0,223.0,119.0,2.0,2.0,2.0,0.0,-1,12.0,10.0,5.0,4.0,12.0,12.0,5.0,4.0,2.0,2.0,0.0,0.0,2.166811,3.486596,3.821467
3,0,68.0,137.0,2.0,1.0,0.0,1.0,-1,12.0,10.0,5.0,4.0,12.0,12.0,5.0,4.0,2.0,2.0,0.0,0.0,2.259244,3.592401,3.460103
4,1,425.0,225.0,2.0,2.0,1.0,0.0,-1,13.0,11.0,5.0,7.0,18.0,15.0,4.0,10.0,3.0,4.0,1.0,0.0,2.424278,3.414191,3.282876

In [150]:
result = X["full_time_home_goals"]-X["full_time_away_goals"]
for i, val in enumerate(result):
    if val<0:
        result[i]=0
    elif val==0:    
        result[i]=1
    else:
        result[i]=2
print(result)

X["Result"] = result

0        1.0
1        1.0
2        1.0
3        2.0
4        1.0
        ...
39987    0.0
39988    2.0
39989    0.0
39990    1.0
39991    1.0
Length: 39992, dtype: float64

In [151]:
print(X["Result"].value_counts())

2.0    17702
0.0    11651
1.0    10639
Name: Result, dtype: int64

In [152]:
y = X["Result"]

X.drop(['Result'],axis=1, inplace=True)
X = X[fir_cols]

X

,Division,home_team,away_team,Referee,home_coef,draw_coef,away_coef
0,0,152.0,426.0,-1,3.627690,3.577721,2.198600
1,0,216.0,341.0,-1,1.608321,4.251999,6.533805
2,0,223.0,119.0,-1,2.166811,3.486596,3.821467
3,0,68.0,137.0,-1,2.259244,3.592401,3.460103
4,1,425.0,225.0,-1,2.424278,3.414191,3.282876
...,...,...,...,...,...,...,...
39987,15,231.0,309.0,-1,2.102645,3.404282,4.155226
39988,15,248.0,398.0,-1,1.340170,5.956310,10.423542
39989,15,453.0,126.0,-1,1.963689,3.506588,4.638715
39990,13,164.0,403.0,-1,4.050577,3.852988,1.985771
39991,6,271.0,269.0,-1,1.732761,3.924194,5.616183

In [153]:
y

0        1.0
1        1.0
2        1.0
3        2.0
4        1.0
        ...
39987    0.0
39988    2.0
39989    0.0
39990    1.0
39991    1.0
Name: Result, Length: 39992, dtype: float64

In [154]:
std_sc = StandardScaler()
std_sc.fit(X)
X_temp = X.copy()

X_temp = std_sc.transform(X)

X = X_temp

In [158]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, shuffle=True, stratify=y)

from sklearn.metrics import accuracy_score

def get_accuracy(y_pred, y):
    return accuracy_score(y_pred, y)

In [160]:
from catboost import CatBoostClassifier

def run_model(MODEL):
    MODEL.fit(X_train, y_train)

    pred_train = MODEL.predict(X_train)

    print( "Train acc = ",get_accuracy(y_train, pred_train) )

    pred_val = MODEL.predict(X_test)
    print( "Validation acc = ",get_accuracy(y_test, pred_val) )


    return MODEL 

CBC = CatBoostClassifier(iterations=500, learning_rate=0.1) #loss_function='CrossEntropy')
CBC = run_model(CBC)
CBC.save_model("submission/CBC.cbm",format="cbm")

0:	learn: 1.0808863	total: 14.1ms	remaining: 7.06s
1:	learn: 1.0672245	total: 27.3ms	remaining: 6.81s
2:	learn: 1.0566544	total: 38.6ms	remaining: 6.4s
3:	learn: 1.0475176	total: 57.8ms	remaining: 7.17s
4:	learn: 1.0400975	total: 71.3ms	remaining: 7.06s
5:	learn: 1.0338448	total: 83.7ms	remaining: 6.89s
6:	learn: 1.0290393	total: 95.7ms	remaining: 6.74s
7:	learn: 1.0248593	total: 106ms	remaining: 6.51s
8:	learn: 1.0216238	total: 115ms	remaining: 6.29s
9:	learn: 1.0185948	total: 126ms	remaining: 6.16s
10:	learn: 1.0160633	total: 136ms	remaining: 6.03s
11:	learn: 1.0140168	total: 147ms	remaining: 5.96s
12:	learn: 1.0121377	total: 156ms	remaining: 5.86s
13:	learn: 1.0107737	total: 164ms	remaining: 5.7s
14:	learn: 1.0095820	total: 176ms	remaining: 5.68s
15:	learn: 1.0084637	total: 184ms	remaining: 5.55s
16:	learn: 1.0074492	total: 193ms	remaining: 5.47s
17:	learn: 1.0067086	total: 200ms	remaining: 5.37s
18:	learn: 1.0060243	total: 210ms	remaining: 5.32s
19:	learn: 1.0054993	total: 223ms	remaining: 5.34s
20:	learn: 1.0048625	total: 247ms	remaining: 5.63s
21:	learn: 1.0042787	total: 262ms	remaining: 5.69s
22:	learn: 1.0038054	total: 277ms	remaining: 5.75s
23:	learn: 1.0034436	total: 291ms	remaining: 5.76s
24:	learn: 1.0030281	total: 302ms	remaining: 5.74s
25:	learn: 1.0026501	total: 312ms	remaining: 5.68s
26:	learn: 1.0024036	total: 330ms	remaining: 5.78s
27:	learn: 1.0020711	total: 343ms	remaining: 5.78s
28:	learn: 1.0017932	total: 355ms	remaining: 5.77s
29:	learn: 1.0015212	total: 364ms	remaining: 5.7s
30:	learn: 1.0013402	total: 374ms	remaining: 5.66s
31:	learn: 1.0011208	total: 385ms	remaining: 5.63s
32:	learn: 1.0009281	total: 396ms	remaining: 5.6s
33:	learn: 1.0007101	total: 408ms	remaining: 5.59s
34:	learn: 1.0005259	total: 417ms	remaining: 5.53s
35:	learn: 1.0002668	total: 431ms	remaining: 5.55s
36:	learn: 1.0000570	total: 447ms	remaining: 5.6s
37:	learn: 0.9998232	total: 466ms	remaining: 5.66s
38:	learn: 0.9996656	total: 483ms	remaining: 5.71s
39:	learn: 0.9994754	total: 495ms	remaining: 5.7s
40:	learn: 0.9993261	total: 507ms	remaining: 5.67s
41:	learn: 0.9991555	total: 517ms	remaining: 5.64s
42:	learn: 0.9989566	total: 527ms	remaining: 5.6s
43:	learn: 0.9987359	total: 540ms	remaining: 5.59s
44:	learn: 0.9985623	total: 552ms	remaining: 5.58s
45:	learn: 0.9983378	total: 561ms	remaining: 5.54s
46:	learn: 0.9981273	total: 576ms	remaining: 5.55s
47:	learn: 0.9979807	total: 586ms	remaining: 5.52s
48:	learn: 0.9978518	total: 595ms	remaining: 5.47s
49:	learn: 0.9976722	total: 605ms	remaining: 5.45s
50:	learn: 0.9975529	total: 616ms	remaining: 5.43s
51:	learn: 0.9973531	total: 627ms	remaining: 5.4s
52:	learn: 0.9972411	total: 651ms	remaining: 5.49s
53:	learn: 0.9970508	total: 667ms	remaining: 5.51s
54:	learn: 0.9968505	total: 677ms	remaining: 5.48s
55:	learn: 0.9966455	total: 692ms	remaining: 5.49s
56:	learn: 0.9964920	total: 705ms	remaining: 5.48s
57:	learn: 0.9963414	total: 715ms	remaining: 5.45s
58:	learn: 0.9962394	total: 723ms	remaining: 5.41s
59:	learn: 0.9960729	total: 735ms	remaining: 5.39s
60:	learn: 0.9958675	total: 747ms	remaining: 5.38s
61:	learn: 0.9957553	total: 755ms	remaining: 5.33s
62:	learn: 0.9956435	total: 766ms	remaining: 5.31s
63:	learn: 0.9955772	total: 773ms	remaining: 5.27s
64:	learn: 0.9954694	total: 788ms	remaining: 5.27s
65:	learn: 0.9953850	total: 800ms	remaining: 5.26s
66:	learn: 0.9952527	total: 808ms	remaining: 5.22s
67:	learn: 0.9950909	total: 818ms	remaining: 5.2s
68:	learn: 0.9949548	total: 827ms	remaining: 5.17s
69:	learn: 0.9948213	total: 838ms	remaining: 5.15s
70:	learn: 0.9946906	total: 849ms	remaining: 5.13s
71:	learn: 0.9945296	total: 865ms	remaining: 5.14s
72:	learn: 0.9943493	total: 877ms	remaining: 5.13s
73:	learn: 0.9941612	total: 888ms	remaining: 5.11s
74:	learn: 0.9939913	total: 900ms	remaining: 5.1s
75:	learn: 0.9938861	total: 912ms	remaining: 5.09s
76:	learn: 0.9937523	total: 921ms	remaining: 5.06s
77:	learn: 0.9936333	total: 933ms	remaining: 5.05s
78:	learn: 0.9935174	total: 947ms	remaining: 5.05s
79:	learn: 0.9934114	total: 955ms	remaining: 5.01s
80:	learn: 0.9932771	total: 969ms	remaining: 5.01s
81:	learn: 0.9931150	total: 980ms	remaining: 5s
82:	learn: 0.9929477	total: 988ms	remaining: 4.96s
83:	learn: 0.9928443	total: 999ms	remaining: 4.95s
84:	learn: 0.9927898	total: 1.01s	remaining: 4.93s
85:	learn: 0.9926663	total: 1.02s	remaining: 4.9s
86:	learn: 0.9925294	total: 1.03s	remaining: 4.89s
87:	learn: 0.9923338	total: 1.04s	remaining: 4.88s
88:	learn: 0.9922223	total: 1.05s	remaining: 4.86s
89:	learn: 0.9920323	total: 1.07s	remaining: 4.86s
90:	learn: 0.9918993	total: 1.08s	remaining: 4.86s
91:	learn: 0.9918013	total: 1.09s	remaining: 4.84s
92:	learn: 0.9916900	total: 1.1s	remaining: 4.81s
93:	learn: 0.9915782	total: 1.11s	remaining: 4.79s
94:	learn: 0.9914638	total: 1.12s	remaining: 4.77s
95:	learn: 0.9913305	total: 1.13s	remaining: 4.76s
96:	learn: 0.9911868	total: 1.14s	remaining: 4.75s
97:	learn: 0.9910426	total: 1.15s	remaining: 4.74s
98:	learn: 0.9909721	total: 1.17s	remaining: 4.72s
99:	learn: 0.9908019	total: 1.18s	remaining: 4.73s
100:	learn: 0.9907379	total: 1.2s	remaining: 4.73s
101:	learn: 0.9906360	total: 1.21s	remaining: 4.71s
102:	learn: 0.9904551	total: 1.22s	remaining: 4.71s
103:	learn: 0.9903575	total: 1.24s	remaining: 4.71s
104:	learn: 0.9901897	total: 1.25s	remaining: 4.7s
105:	learn: 0.9900518	total: 1.27s	remaining: 4.73s
106:	learn: 0.9898648	total: 1.29s	remaining: 4.75s
107:	learn: 0.9897899	total: 1.32s	remaining: 4.78s
108:	learn: 0.9896716	total: 1.33s	remaining: 4.79s
109:	learn: 0.9895072	total: 1.35s	remaining: 4.79s
110:	learn: 0.9893410	total: 1.37s	remaining: 4.8s
111:	learn: 0.9892440	total: 1.38s	remaining: 4.78s
112:	learn: 0.9891565	total: 1.39s	remaining: 4.78s
113:	learn: 0.9889483	total: 1.41s	remaining: 4.77s
114:	learn: 0.9888157	total: 1.42s	remaining: 4.75s
115:	learn: 0.9887098	total: 1.43s	remaining: 4.73s
116:	learn: 0.9885849	total: 1.44s	remaining: 4.72s
117:	learn: 0.9884765	total: 1.45s	remaining: 4.71s
118:	learn: 0.9883788	total: 1.47s	remaining: 4.7s
119:	learn: 0.9882552	total: 1.49s	remaining: 4.71s
120:	learn: 0.9880581	total: 1.5s	remaining: 4.7s
121:	learn: 0.9879808	total: 1.51s	remaining: 4.68s
122:	learn: 0.9878151	total: 1.52s	remaining: 4.67s
123:	learn: 0.9877134	total: 1.54s	remaining: 4.66s
124:	learn: 0.9875994	total: 1.55s	remaining: 4.65s
125:	learn: 0.9874543	total: 1.56s	remaining: 4.63s
126:	learn: 0.9872887	total: 1.57s	remaining: 4.62s
127:	learn: 0.9871667	total: 1.59s	remaining: 4.61s
128:	learn: 0.9870822	total: 1.6s	remaining: 4.59s
129:	learn: 0.9870005	total: 1.6s	remaining: 4.57s
130:	learn: 0.9868205	total: 1.62s	remaining: 4.56s
131:	learn: 0.9867208	total: 1.63s	remaining: 4.55s
132:	learn: 0.9866265	total: 1.64s	remaining: 4.53s
133:	learn: 0.9864876	total: 1.66s	remaining: 4.52s
134:	learn: 0.9863560	total: 1.67s	remaining: 4.51s
135:	learn: 0.9861900	total: 1.68s	remaining: 4.5s
136:	learn: 0.9860845	total: 1.7s	remaining: 4.51s
137:	learn: 0.9859961	total: 1.72s	remaining: 4.52s
138:	learn: 0.9858995	total: 1.74s	remaining: 4.51s
139:	learn: 0.9858128	total: 1.75s	remaining: 4.5s
140:	learn: 0.9857118	total: 1.76s	remaining: 4.48s
141:	learn: 0.9856033	total: 1.77s	remaining: 4.47s
142:	learn: 0.9855000	total: 1.79s	remaining: 4.46s
143:	learn: 0.9853999	total: 1.8s	remaining: 4.45s
144:	learn: 0.9852871	total: 1.81s	remaining: 4.43s
145:	learn: 0.9851879	total: 1.82s	remaining: 4.42s
146:	learn: 0.9850426	total: 1.83s	remaining: 4.4s
147:	learn: 0.9848501	total: 1.84s	remaining: 4.39s
148:	learn: 0.9847141	total: 1.85s	remaining: 4.37s
149:	learn: 0.9845414	total: 1.87s	remaining: 4.36s
150:	learn: 0.9843042	total: 1.88s	remaining: 4.35s
151:	learn: 0.9841919	total: 1.9s	remaining: 4.34s
152:	learn: 0.9840753	total: 1.91s	remaining: 4.34s
153:	learn: 0.9839265	total: 1.93s	remaining: 4.35s
154:	learn: 0.9837986	total: 1.95s	remaining: 4.34s
155:	learn: 0.9836515	total: 1.96s	remaining: 4.33s
156:	learn: 0.9835185	total: 1.98s	remaining: 4.32s
157:	learn: 0.9833776	total: 2s	remaining: 4.33s
158:	learn: 0.9832480	total: 2.01s	remaining: 4.32s
159:	learn: 0.9830717	total: 2.03s	remaining: 4.31s
160:	learn: 0.9829856	total: 2.04s	remaining: 4.31s
161:	learn: 0.9828768	total: 2.06s	remaining: 4.3s
162:	learn: 0.9827437	total: 2.07s	remaining: 4.29s
163:	learn: 0.9825640	total: 2.08s	remaining: 4.27s
164:	learn: 0.9824358	total: 2.1s	remaining: 4.26s
165:	learn: 0.9822666	total: 2.1s	remaining: 4.23s
166:	learn: 0.9821476	total: 2.12s	remaining: 4.22s
167:	learn: 0.9820203	total: 2.13s	remaining: 4.22s
168:	learn: 0.9819210	total: 2.15s	remaining: 4.21s
169:	learn: 0.9818057	total: 2.17s	remaining: 4.2s
170:	learn: 0.9816964	total: 2.18s	remaining: 4.2s
171:	learn: 0.9816233	total: 2.19s	remaining: 4.18s
172:	learn: 0.9814897	total: 2.2s	remaining: 4.17s
173:	learn: 0.9813575	total: 2.22s	remaining: 4.15s
174:	learn: 0.9812454	total: 2.23s	remaining: 4.14s
175:	learn: 0.9811270	total: 2.24s	remaining: 4.13s
176:	learn: 0.9809608	total: 2.25s	remaining: 4.1s
177:	learn: 0.9808573	total: 2.26s	remaining: 4.09s
178:	learn: 0.9807276	total: 2.27s	remaining: 4.07s
179:	learn: 0.9805943	total: 2.28s	remaining: 4.06s
180:	learn: 0.9804500	total: 2.29s	remaining: 4.04s
181:	learn: 0.9803794	total: 2.3s	remaining: 4.03s
182:	learn: 0.9802433	total: 2.31s	remaining: 4.01s
183:	learn: 0.9801219	total: 2.33s	remaining: 4s
184:	learn: 0.9799808	total: 2.34s	remaining: 3.99s
185:	learn: 0.9798483	total: 2.36s	remaining: 3.98s
186:	learn: 0.9797776	total: 2.37s	remaining: 3.96s
187:	learn: 0.9796310	total: 2.38s	remaining: 3.95s
188:	learn: 0.9795289	total: 2.39s	remaining: 3.94s
189:	learn: 0.9794676	total: 2.4s	remaining: 3.92s
190:	learn: 0.9793509	total: 2.42s	remaining: 3.91s
191:	learn: 0.9792437	total: 2.43s	remaining: 3.9s
192:	learn: 0.9791590	total: 2.44s	remaining: 3.88s
193:	learn: 0.9790345	total: 2.45s	remaining: 3.87s
194:	learn: 0.9789215	total: 2.46s	remaining: 3.85s
195:	learn: 0.9788026	total: 2.48s	remaining: 3.84s
196:	learn: 0.9786956	total: 2.49s	remaining: 3.83s
197:	learn: 0.9785656	total: 2.5s	remaining: 3.81s
198:	learn: 0.9784711	total: 2.51s	remaining: 3.79s
199:	learn: 0.9783010	total: 2.52s	remaining: 3.78s
200:	learn: 0.9781475	total: 2.54s	remaining: 3.77s
201:	learn: 0.9780161	total: 2.55s	remaining: 3.76s
202:	learn: 0.9778792	total: 2.57s	remaining: 3.76s
203:	learn: 0.9777707	total: 2.58s	remaining: 3.75s
204:	learn: 0.9776491	total: 2.6s	remaining: 3.73s
205:	learn: 0.9775205	total: 2.61s	remaining: 3.72s
206:	learn: 0.9773572	total: 2.62s	remaining: 3.71s
207:	learn: 0.9772647	total: 2.63s	remaining: 3.7s
208:	learn: 0.9771656	total: 2.64s	remaining: 3.68s
209:	learn: 0.9770329	total: 2.65s	remaining: 3.67s
210:	learn: 0.9769265	total: 2.67s	remaining: 3.65s
211:	learn: 0.9768483	total: 2.68s	remaining: 3.64s
212:	learn: 0.9767148	total: 2.69s	remaining: 3.63s
213:	learn: 0.9766016	total: 2.7s	remaining: 3.61s
214:	learn: 0.9764776	total: 2.72s	remaining: 3.6s
215:	learn: 0.9764199	total: 2.73s	remaining: 3.59s
216:	learn: 0.9762436	total: 2.74s	remaining: 3.57s
217:	learn: 0.9760614	total: 2.77s	remaining: 3.58s
218:	learn: 0.9759150	total: 2.78s	remaining: 3.57s
219:	learn: 0.9757680	total: 2.79s	remaining: 3.56s
220:	learn: 0.9756045	total: 2.81s	remaining: 3.54s
221:	learn: 0.9754840	total: 2.82s	remaining: 3.53s
222:	learn: 0.9753733	total: 2.83s	remaining: 3.52s
223:	learn: 0.9752475	total: 2.84s	remaining: 3.5s
224:	learn: 0.9751298	total: 2.85s	remaining: 3.49s
225:	learn: 0.9750567	total: 2.87s	remaining: 3.48s
226:	learn: 0.9749415	total: 2.88s	remaining: 3.47s
227:	learn: 0.9748010	total: 2.9s	remaining: 3.46s
228:	learn: 0.9746317	total: 2.92s	remaining: 3.46s
229:	learn: 0.9745238	total: 2.94s	remaining: 3.45s
230:	learn: 0.9744255	total: 2.96s	remaining: 3.45s
231:	learn: 0.9743101	total: 2.98s	remaining: 3.44s
232:	learn: 0.9742319	total: 2.99s	remaining: 3.43s
233:	learn: 0.9740597	total: 3s	remaining: 3.42s
234:	learn: 0.9739122	total: 3.02s	remaining: 3.4s
235:	learn: 0.9738493	total: 3.02s	remaining: 3.38s
236:	learn: 0.9737273	total: 3.03s	remaining: 3.36s
237:	learn: 0.9735997	total: 3.04s	remaining: 3.35s
238:	learn: 0.9735444	total: 3.05s	remaining: 3.33s
239:	learn: 0.9734142	total: 3.06s	remaining: 3.31s
240:	learn: 0.9732978	total: 3.06s	remaining: 3.29s
241:	learn: 0.9731218	total: 3.07s	remaining: 3.28s
242:	learn: 0.9730115	total: 3.08s	remaining: 3.26s
243:	learn: 0.9729165	total: 3.09s	remaining: 3.24s
244:	learn: 0.9728167	total: 3.1s	remaining: 3.22s
245:	learn: 0.9727060	total: 3.1s	remaining: 3.21s
246:	learn: 0.9726207	total: 3.11s	remaining: 3.19s
247:	learn: 0.9725065	total: 3.12s	remaining: 3.17s
248:	learn: 0.9723252	total: 3.13s	remaining: 3.15s
249:	learn: 0.9721864	total: 3.14s	remaining: 3.14s
250:	learn: 0.9720566	total: 3.15s	remaining: 3.13s
251:	learn: 0.9719312	total: 3.16s	remaining: 3.11s
252:	learn: 0.9718572	total: 3.17s	remaining: 3.09s
253:	learn: 0.9717254	total: 3.18s	remaining: 3.08s
254:	learn: 0.9716271	total: 3.19s	remaining: 3.06s
255:	learn: 0.9714216	total: 3.2s	remaining: 3.05s
256:	learn: 0.9712592	total: 3.21s	remaining: 3.04s
257:	learn: 0.9711734	total: 3.22s	remaining: 3.02s
258:	learn: 0.9710757	total: 3.23s	remaining: 3.01s
259:	learn: 0.9709690	total: 3.24s	remaining: 2.99s
260:	learn: 0.9708629	total: 3.25s	remaining: 2.97s
261:	learn: 0.9706931	total: 3.26s	remaining: 2.96s
262:	learn: 0.9706127	total: 3.27s	remaining: 2.94s
263:	learn: 0.9704776	total: 3.28s	remaining: 2.93s
264:	learn: 0.9703346	total: 3.29s	remaining: 2.91s
265:	learn: 0.9701852	total: 3.29s	remaining: 2.9s
266:	learn: 0.9700719	total: 3.3s	remaining: 2.88s
267:	learn: 0.9698978	total: 3.31s	remaining: 2.87s
268:	learn: 0.9697864	total: 3.32s	remaining: 2.85s
269:	learn: 0.9697064	total: 3.32s	remaining: 2.83s
270:	learn: 0.9695684	total: 3.33s	remaining: 2.81s
271:	learn: 0.9694692	total: 3.34s	remaining: 2.8s
272:	learn: 0.9693716	total: 3.35s	remaining: 2.79s
273:	learn: 0.9692637	total: 3.36s	remaining: 2.77s
274:	learn: 0.9691748	total: 3.37s	remaining: 2.76s
275:	learn: 0.9689976	total: 3.38s	remaining: 2.74s
276:	learn: 0.9689151	total: 3.38s	remaining: 2.73s
277:	learn: 0.9688559	total: 3.39s	remaining: 2.71s
278:	learn: 0.9687615	total: 3.4s	remaining: 2.69s
279:	learn: 0.9686159	total: 3.41s	remaining: 2.68s
280:	learn: 0.9684822	total: 3.42s	remaining: 2.66s
281:	learn: 0.9683759	total: 3.43s	remaining: 2.65s
282:	learn: 0.9682456	total: 3.44s	remaining: 2.64s
283:	learn: 0.9680995	total: 3.45s	remaining: 2.62s
284:	learn: 0.9680468	total: 3.45s	remaining: 2.61s
285:	learn: 0.9679072	total: 3.46s	remaining: 2.59s
286:	learn: 0.9678372	total: 3.47s	remaining: 2.58s
287:	learn: 0.9677534	total: 3.48s	remaining: 2.56s
288:	learn: 0.9676505	total: 3.49s	remaining: 2.55s
289:	learn: 0.9674985	total: 3.5s	remaining: 2.53s
290:	learn: 0.9673791	total: 3.5s	remaining: 2.52s
291:	learn: 0.9671829	total: 3.51s	remaining: 2.5s
292:	learn: 0.9670984	total: 3.52s	remaining: 2.49s
293:	learn: 0.9669602	total: 3.53s	remaining: 2.47s
294:	learn: 0.9668735	total: 3.54s	remaining: 2.46s
295:	learn: 0.9667571	total: 3.54s	remaining: 2.44s
296:	learn: 0.9665749	total: 3.56s	remaining: 2.43s
297:	learn: 0.9664407	total: 3.56s	remaining: 2.42s
298:	learn: 0.9663399	total: 3.57s	remaining: 2.4s
299:	learn: 0.9662468	total: 3.58s	remaining: 2.39s
300:	learn: 0.9661766	total: 3.59s	remaining: 2.37s
301:	learn: 0.9660843	total: 3.6s	remaining: 2.36s
302:	learn: 0.9659906	total: 3.6s	remaining: 2.34s
303:	learn: 0.9659033	total: 3.61s	remaining: 2.33s
304:	learn: 0.9658454	total: 3.62s	remaining: 2.31s
305:	learn: 0.9657574	total: 3.63s	remaining: 2.3s
306:	learn: 0.9656254	total: 3.64s	remaining: 2.29s
307:	learn: 0.9655524	total: 3.65s	remaining: 2.27s
308:	learn: 0.9654558	total: 3.65s	remaining: 2.26s
309:	learn: 0.9653612	total: 3.66s	remaining: 2.25s
310:	learn: 0.9652605	total: 3.67s	remaining: 2.23s
311:	learn: 0.9651164	total: 3.68s	remaining: 2.22s
312:	learn: 0.9650149	total: 3.69s	remaining: 2.2s
313:	learn: 0.9648411	total: 3.7s	remaining: 2.19s
314:	learn: 0.9647518	total: 3.71s	remaining: 2.18s
315:	learn: 0.9646046	total: 3.72s	remaining: 2.16s
316:	learn: 0.9645038	total: 3.73s	remaining: 2.15s
317:	learn: 0.9643229	total: 3.73s	remaining: 2.14s
318:	learn: 0.9642139	total: 3.74s	remaining: 2.12s
319:	learn: 0.9641304	total: 3.75s	remaining: 2.11s
320:	learn: 0.9639859	total: 3.77s	remaining: 2.1s
321:	learn: 0.9639248	total: 3.8s	remaining: 2.1s
322:	learn: 0.9637854	total: 3.81s	remaining: 2.09s
323:	learn: 0.9636831	total: 3.82s	remaining: 2.08s
324:	learn: 0.9634826	total: 3.83s	remaining: 2.06s
325:	learn: 0.9633959	total: 3.84s	remaining: 2.05s
326:	learn: 0.9633101	total: 3.85s	remaining: 2.04s
327:	learn: 0.9632272	total: 3.86s	remaining: 2.02s
328:	learn: 0.9630734	total: 3.87s	remaining: 2.01s
329:	learn: 0.9629937	total: 3.88s	remaining: 2s
330:	learn: 0.9629113	total: 3.89s	remaining: 1.99s
331:	learn: 0.9627927	total: 3.9s	remaining: 1.97s
332:	learn: 0.9626870	total: 3.91s	remaining: 1.96s
333:	learn: 0.9626045	total: 3.92s	remaining: 1.95s
334:	learn: 0.9624634	total: 3.92s	remaining: 1.93s
335:	learn: 0.9623685	total: 3.93s	remaining: 1.92s
336:	learn: 0.9622702	total: 3.94s	remaining: 1.91s
337:	learn: 0.9621651	total: 3.95s	remaining: 1.89s
338:	learn: 0.9620993	total: 3.96s	remaining: 1.88s
339:	learn: 0.9620041	total: 3.97s	remaining: 1.87s
340:	learn: 0.9618729	total: 3.98s	remaining: 1.85s
341:	learn: 0.9617735	total: 3.99s	remaining: 1.84s
342:	learn: 0.9616974	total: 4s	remaining: 1.83s
343:	learn: 0.9616362	total: 4.01s	remaining: 1.82s
344:	learn: 0.9615213	total: 4.02s	remaining: 1.8s
345:	learn: 0.9614071	total: 4.03s	remaining: 1.79s
346:	learn: 0.9612821	total: 4.04s	remaining: 1.78s
347:	learn: 0.9611470	total: 4.04s	remaining: 1.77s
348:	learn: 0.9610617	total: 4.05s	remaining: 1.75s
349:	learn: 0.9609954	total: 4.06s	remaining: 1.74s
350:	learn: 0.9608729	total: 4.07s	remaining: 1.73s
351:	learn: 0.9607403	total: 4.08s	remaining: 1.72s
352:	learn: 0.9606293	total: 4.09s	remaining: 1.7s
353:	learn: 0.9605055	total: 4.1s	remaining: 1.69s
354:	learn: 0.9604309	total: 4.1s	remaining: 1.68s
355:	learn: 0.9603124	total: 4.11s	remaining: 1.66s
356:	learn: 0.9602314	total: 4.12s	remaining: 1.65s
357:	learn: 0.9601108	total: 4.13s	remaining: 1.64s
358:	learn: 0.9600438	total: 4.14s	remaining: 1.63s
359:	learn: 0.9599892	total: 4.14s	remaining: 1.61s
360:	learn: 0.9598827	total: 4.15s	remaining: 1.6s
361:	learn: 0.9597893	total: 4.16s	remaining: 1.59s
362:	learn: 0.9596297	total: 4.18s	remaining: 1.58s
363:	learn: 0.9595231	total: 4.19s	remaining: 1.56s
364:	learn: 0.9594364	total: 4.19s	remaining: 1.55s
365:	learn: 0.9593093	total: 4.2s	remaining: 1.54s
366:	learn: 0.9591954	total: 4.21s	remaining: 1.52s
367:	learn: 0.9591484	total: 4.22s	remaining: 1.51s
368:	learn: 0.9590429	total: 4.23s	remaining: 1.5s
369:	learn: 0.9589633	total: 4.24s	remaining: 1.49s
370:	learn: 0.9588598	total: 4.24s	remaining: 1.48s
371:	learn: 0.9587756	total: 4.25s	remaining: 1.46s
372:	learn: 0.9586207	total: 4.26s	remaining: 1.45s
373:	learn: 0.9585586	total: 4.27s	remaining: 1.44s
374:	learn: 0.9585071	total: 4.28s	remaining: 1.43s
375:	learn: 0.9583869	total: 4.29s	remaining: 1.41s
376:	learn: 0.9583064	total: 4.29s	remaining: 1.4s
377:	learn: 0.9582114	total: 4.3s	remaining: 1.39s
378:	learn: 0.9580692	total: 4.31s	remaining: 1.38s
379:	learn: 0.9579086	total: 4.32s	remaining: 1.36s
380:	learn: 0.9578288	total: 4.33s	remaining: 1.35s
381:	learn: 0.9577799	total: 4.34s	remaining: 1.34s
382:	learn: 0.9576711	total: 4.35s	remaining: 1.33s
383:	learn: 0.9575631	total: 4.36s	remaining: 1.32s
384:	learn: 0.9574127	total: 4.38s	remaining: 1.31s
385:	learn: 0.9572689	total: 4.39s	remaining: 1.3s
386:	learn: 0.9571740	total: 4.4s	remaining: 1.28s
387:	learn: 0.9570883	total: 4.41s	remaining: 1.27s

In [157]:
model = CatBoostClassifier(iterations=10, learning_rate=0.1) #loss_function='CrossEntropy')
model.load_model("CBC.cbm",format="cbm")

In [138]:
X_train.shape

(39987, 7)

In [139]:
X_train

array([[-0.71364631, -0.19257898,  1.09840647, ..., -0.54723137,
        -0.06298778,  0.34904648],
       [ 0.99417394,  1.03546715, -1.46926244, ...,  0.14186222,
        -0.39949091, -0.50495058],
       [-1.09316192,  0.11269803, -1.58723642, ..., -0.47738908,
         0.05198112,  0.0190366 ],
       ...,
       [-0.90340412, -0.65743259, -1.63581394, ...,  0.08429971,
        -0.48356302, -0.46316289],
       [ 0.04538491,  1.15341508,  1.59806096, ..., -0.47897487,
        -0.08737509,  0.0880558 ],
       [ 0.80441614, -0.85169978,  0.30728686, ..., -0.15105747,
        -0.57607272, -0.27790751]])